export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART'
export const ADD_TO_BUY = 'ADD_TO_BUY'
export const REMOVE_ITEM_BUY = 'REMOVE_ITEM_BUY'
export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO'

