export const ADMIN_PRODUCTS_REQUEST = 'ADMIN_PRODUCTS_REQUEST'
export const ADMIN_PRODUCTS_SUCCESS = 'ADMIN_PRODUCTS_SUCCESS'
export const ADMIN_PRODUCTS_FAIL = 'ADMIN_PRODUCTS_FAIL'

export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL'

export const NEW_PRODUCT_REQUEST = 'NEW_PRODUCT_REQUEST'
export const NEW_PRODUCT_SUCCESS = 'NEW_PRODUCT_SUCCESS'
export const NEW_PRODUCT_RESET = 'NEW_PRODUCT_RESET'
export const NEW_PRODUCT_FAIL = 'NEW_PRODUCT_FAIL'

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_RESET'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCT_RESET'
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL'


export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

export const RELATED_PRODUCTS_REQUEST = 'RELATED_PRODUCTS_REQUEST'
export const RELATED_PRODUCTS_SUCCESS = 'RELATED_PRODUCTS_SUCCESS'
export const RELATED_PRODUCTS_FAIL = 'RELATED_PRODUCTS_FAIL'

export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST'
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS'
export const CREATE_CATEGORY_RESET = 'CREATE_CATEGORY_RESET'
export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL'

export const ALL_CATEGORY_REQUEST = 'ALL_CATEGORY_REQUEST'
export const ALL_CATEGORY_SUCCESS = 'ALL_CATEGORY_SUCCESS'
export const ALL_CATEGORY_FAIL = 'ALL_CATEGORY_FAIL'

export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'
export const UPDATE_CATEGORY_RESET = 'UPDATE_CATEGORY_RESET'
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL'

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_RESET = 'DELETE_CATEGORY_RESET'
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL'

export const UPDATE_BANNER_REQUEST = 'UPDATE_BANNER_REQUEST'
export const UPDATE_BANNER_SUCCESS = 'UPDATE_BANNER_SUCCESS'
export const UPDATE_BANNER_FAIL = 'UPDATE_BANNER_FAIL'

export const UPDATE_SIDEIMAGE_REQUEST = 'UPDATE_SIDEIMAGE_REQUEST'
export const UPDATE_SIDEIMAGE_SUCCESS = 'UPDATE_SIDEIMAGE_SUCCESS'
export const UPDATE_SIDEIMAGE_FAIL = 'UPDATE_SIDEIMAGE_FAIL'

export const GET_SIDEIMAGE_REQUEST = 'GET_SIDEIMAGE_REQUEST'
export const GET_SIDEIMAGE_SUCCESS = 'GET_SIDEIMAGE_SUCCESS'
export const GET_SIDEIMAGE_FAIL = 'GET_SIDEIMAGE_FAIL'

export const UPDATE_STOCK_REQUEST = 'UPDATE_STOCK_REQUEST'
export const UPDATE_STOCK_SUCCESS = 'UPDATE_STOCK_SUCCESS'
export const UPDATE_STOCK_FAIL = 'UPDATE_STOCK_FAIL'

export const GET_BANNER_REQUEST = 'GET_BANNER_REQUEST'
export const GET_BANNER_SUCCESS = 'GET_BANNER_SUCCESS'
export const GET_BANNER_FAIL = 'GET_BANNER_FAIL'

export const DELETE_BANNER_REQUEST = 'DELETE_BANNER_REQUEST'
export const DELETE_BANNER_SUCCESS = 'DELETE_BANNER_SUCCESS'
export const DELETE_BANNER_FAIL = 'DELETE_BANNER_FAIL'

export const DELETE_SIDEIMAGE_REQUEST = 'DELETE_SIDEIMAGE_REQUEST'
export const DELETE_SIDEIMAGE_SUCCESS = 'DELETE_SIDEIMAGE_SUCCESS'
export const DELETE_SIDEIMAGE_FAIL = 'DELETE_SIDEIMAGE_FAIL'

export const TOP_PRODUCT_REQUEST = 'TOP_PRODUCT_REQUEST'
export const TOP_PRODUCT_SUCCESS = 'TOP_PRODUCT_SUCCESS'
export const TOP_PRODUCT_FAIL = 'TOP_PRODUCT_FAIL'
export const TOP_PRODUCT_RESET = 'TOP_PRODUCT_RESET'

export const LOAD_ALL_PRODUCTS_REQUEST = 'LOAD_ALL_PRODUCTS_REQUEST'
export const LOAD_ALL_PRODUCTS_SUCCESS = 'LOAD_ALL_PRODUCTS_SUCCESS'
export const LOAD_ALL_PRODUCTS_FAIL = 'LOAD_ALL_PRODUCTS_FAIL'
export const LOAD_ALL_PRODUCTS_RESET = 'LOAD_ALL_PRODUCTS_RESET'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'


